export const EMPLOYEE_SAVE = "EMPLOYEE_SAVE";
export const EMPLOYEE_SAVE_PENDING = "EMPLOYEE_SAVE_PENDING";
export const EMPLOYEE_SAVE_FULFILLED = "EMPLOYEE_SAVE_FULFILLED";
export const EMPLOYEE_SAVE_REJECTED = "EMPLOYEE_SAVE_REJECTED";
export const EMPLOYEE_SAVED = "EMPLOYEE_SAVED";

export const EMPLOYEE_SHOWALL = "EMPLOYEE_SHOWALL";
export const EMPLOYEE_SHOWALL_PENDING = "EMPLOYEE_SHOWALL_PENDING";
export const EMPLOYEE_SHOWALL_FULFILLED = "EMPLOYEE_SHOWALL_FULFILLED";
export const EMPLOYEE_SHOWALL_REJECTED = "EMPLOYEE_SHOWALL_REJECTED";
export const EMPLOYEE_SHOWED = "EMPLOYEE_SHOWED";

export const ADD_ARTICLE="ADD_ARTICLE";
export const NEW_CLICKED="NEW_CLICKED";
export const NEW_SAVED="NEW_SAVED"; 
export const NEW_CLEAR="NEW_CLEAR";
export const EDIT_CLICKED="EDIT_CLICKED"; 
export const EDIT_SHOW="EDIT_SHOW"; 
export const EDIT_SAVE="EDIT_SAVE"; 
export const DELETE_CLICKED="DELETE_CLICKED"; 
export const DELETE_DONE="DELETE_DONE";
export const SHOW_LIST="SHOW_LIST";

